- name: Gather facts sample
  hosts: all
  tasks:
   - name: Ansible create file if it doesn't exist example
     file:
      path: "/opt/myfile"
      state: touch
   - name: insert line
     lineinfile:
      path: /opt/myfile
      line: halooo
      create: yes
